name: CoderCo CICD workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          cd matrix-builds
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run tests
        run: |
          cd matrix-builds
          python -m unittests discover

      - name: notify us of success
        run: echo "All tests passed on Python ${{ matrix.python-version }}!"
        if: success()
