name: CoderCo Manual Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Choose Python version"
        required: true
        default: "3.11"
        type: choice
        options:
          - "3.10"
          - "3.11"
          - "3.12"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["${{ github.event.inputs.python-version }}"]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          cd matrix-builds
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run tests
        run: |
          cd matrix-builds
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: notify us of success
        run: echo "All tests passed on Python ${{ matrix.python-version }}!"
        if: success()
